### ISSUE TITLE
Websocket disconnection (or stopping receiving data)

### ISSUE THREAD

**Issue by albertdb** [goincrypto/cryptocom-exchange#1]
Hi,

I observe that sometimes, websocket listens stop yielding data. I even detected rare cases where it never starts receiving data (but only pings).

I honestly think that this is a problem on Crypto.com side, but it would be nice if you could transparently restart connection when prudent a time passes (5m?) and no data is received.

Thanks.

**Comment by mortyspace** [comment]
I Will look at this problem, thanks!

**Comment by mortyspace** [comment]
Closed, if will be reproduced in API v2 will be reopened
