### ISSUE TITLE
Make Coins and Pairs Dynamics.

### ISSUE THREAD

**Issue by guiguid** [goincrypto/cryptocom-exchange#16]
Hi,
in order to not update this library everytime a coin is listed or a pair added,
it could be more affective to let Coin and Pair dynamic, 
and if possible as simple as string.
If not, in the case the exchange list pair faster than the library is updated .... 
I've made this update for my purpose, but not in the python skill to be published, and it works like a charm on new Coin/Pair without even restarting the python script.
cheers

**Comment by mortyspace** [comment]
Done in 0.7, description added in docs, use `sync_pairs()`

**Comment by JulienCoutault** [comment]
Hi @mortyspace 
Why to you keep the files `src/cryptocom/exchange/coins.py` and `src/cryptocom/exchange/pairs.py` since you have this function ?
