### ISSUE TITLE
get_balance( )

### ISSUE THREAD

**Issue by jednicka0** [goincrypto/cryptocom-exchange#17]
Hello im new in programing so sorry if that is stupid question :) 
So i want from get_balance( ) only 1 pair not every ticker for example just CRO ...
when i use .keys( ) it returns all keys like for exapmle  : 
Coin(name='ENJ'), Coin(name='CRO') and so on ... when i use  .get( Coin(name='CRO') it returns none but when i understand it good it should return  Balance(total=0, available=0, in_orders=0, in_stake=0, coin=Coin(name='CRO')

**Comment by samueltayishere** [comment]
At present the function does not accept a filter even though the exchange api supports it.

What you can do is to iterate through using
```
for c, bal in returnedbal.items():
    if 'CRO' in bal.coin.name:
        //do whatever
```

**Comment by mortyspace** [comment]
simple use
```
from cryptocom import exchange as cro
balance = await account.get_balance()
cro = balance[cro.coins.CRO]
print(cro.available, 'available')
```
