### ISSUE TITLE
Websocket V2 API support

### ISSUE THREAD

**Issue by albertdb** [goincrypto/cryptocom-exchange#2]
Hi,

Crypto.com changed API and websocket V1 endpoint doesn't seem to respond anymore. REST V1 still works.

Could you please add support to websocket V2 API. Just making previously implementation calls work again would be enough.

Thank you very much

**Comment by mortyspace** [comment]
Already working on this) I think by end of the week will be available

**Comment by mortyspace** [comment]
@albertdb stuck with private methods, the public methods are ready. Their own endpoints respond with 404 errors) and WebSocket connection doesn't drop when I trying to send a heartbeat. Still beta I think, that's the reason.

**Comment by mortyspace** [comment]
@albertdb Ahah, found my error, missed "Applies To: " xD (WebSockets and what in REST). They just tell us about "commands". Omg, so confusing)

**Comment by albertdb** [comment]
I hope websocket support can be readded soon. Thank you for your efforts.

**Comment by mortyspace** [comment]
Hi man, finally added support from version 0.3) You can account.api or exchange.api.listen and sign=True if want private endpoints
