### ISSUE TITLE
Intermitent INVALID_NONCE errors

### ISSUE THREAD

**Issue by sebaslogen** [goincrypto/cryptocom-exchange#20]
I randomly get the error below and after some minutes or hours, it works again without any change on the commands nor my system.
 'Error: {'id': 5838, 'method': 'private/get-account-summary', 'code': 10007, 'message': 'INVALID_NONCE'}. Status: 400.
 'Error: {'id': 5231, 'method': 'private/create-order', 'code': 10007, 'message': 'INVALID_NONCE'}. Status: 400.

Looking at the docs this happens when my computer's time is >30secs behind the Crypto.com exchange or 1s ahead, I assume the later is the problem. See https://exchange-docs.crypto.com/#invalid_nonce-on-all-requests

Could you add a couple of seconds to the system time generated with the time-python function when signing the transaction with a nonce?

**Comment by mortyspace** [comment]
Probably it's because the request going to cryptocom is too long and we have a timeout of 120secs, will make timeout 25 secs. Try updated 0.7.7 version
