### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by acairon** [goincrypto/cryptocom-exchange#26]
hello im getting this error: 

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001EE672A7CA0>

raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

async def main():
    account = cro.Account(api_key='*', api_secret='*')
    data = await account.get_balance()
    account.
    print(data)

asyncio.run(main())

**Comment by mortyspace** [comment]
what version of python?
