### ISSUE TITLE
error in spread calculation 

### ISSUE THREAD

**Issue by N9neFifty** [goincrypto/cryptocom-exchange#32]
def spread(self) -> float:
        return round_down(self.sells[0].price / self.buys[0].price - 1, 6)`

should be 

    def spread(self) -> float:
        return round_down(self.sells[-1].price / self.buys[0].price - 1, 6)`

I was using the .spread method and notices that the spread for CRO/USDT was returning at 18% once normalized to the last price, so I switched the index of the sell and the spread tightened up to 0.04% which is correct

**Comment by mortyspace** [comment]
Fixed in 0.9.4
