### ISSUE TITLE
Build function for orders crashing for wrong key

### ISSUE THREAD

**Issue by fra87** [goincrypto/cryptocom-exchange#42]
Hello

I'm trying to pull my orders data, but there is an issue when trying to pull the LUNA orders placed before the name change.

What I get is:

```
return await self.account.get_orders_history(pair, start_ts=start_ts, end_ts=end_ts)
  File "#venv location#/lib/python3.9/site-packages/cryptocom/exchange/private.py", line 172, in get_orders_history
    return [
  File "#venv location#/lib/python3.9/site-packages/cryptocom/exchange/private.py", line 173, in <listcomp>
    Order.create_from_api(self.pairs[order["instrument_name"]], order)
KeyError: 'LUNA_USDC'
```

I checked and the LUNA_USDC pair is no more present (it got renamed to LUNC_USDC), but apparently the API returns also the old naming.

I think the pair shall be added back again to avoid losing compatibility with old transactions

**Comment by mortyspace** [comment]
Yes, will think about how to solve it, probably for pairs that were deleted. The best thing is to add delisted flag and always add new pairs to the list. I will fix with dynamic pair creation with default precisions for now

**Comment by fra87** [comment]
@mortyspace do you know when this fix will be released (or if there is any working branch/repo where you are implementing the feature)?

**Comment by mortyspace** [comment]
@fra87 fix is deployed, wait for version update)
